version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.04
      
    steps:
      - checkout
      
      - run: apt-get update -y sudo
      - run: apt-get install make -y sudo
      - run: apt-get install git -y sudo
      - run: apt-get install gcc -y sudo
      - run: apt-get install libncursesw5-dev -y sudo
      - run: apt-get install libcurl4-openssl-dev -y sudo
