version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.04
        command: ["RUN apt-get update -y && apt-get install -y \ make \ gcc \ lincursesw5-dev \ git \ libcurl4-openssl-dev"]
    steps:
      - checkout
      - run: echo "hello world"
