version: 2
jobs:
  build:
    docker: # use the docker executor type; machine and macos executors are also supported
      - image: sundermanwr25/centos_7.3:0.0.1 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      
      - run:
          name: build project
          command: |
             cd /root/project/cReddit && ls && make && make install && ls && export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/cReddit/build && ldconfig && ldconfig -p
      
      - run:
          name: run project
          command: |
             cd /root/project/cReddit && bash './run.sh'
      
          
