version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.04
      
    steps:
      - checkout
      - run: echo "hello world"
      - run: sudo apt-get update -y && sudo apt-get install make git libcursesw5-dev libcurl4-openssl-dev
