version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.04
      
    steps:
      - checkout
      
      - run:
          command: |
            sudo killall apt apt-get
      - run: 
          command: |
            apt-get update -y | apt-get install make -y | apt-get install git -y | apt-get install gcc -y | apt-get install libncursesw5-dev -y | apt-get install libcurl4-openssl-dev -y
