version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.04
      
    steps:
      - checkout
      - run: echo "hello world"
      - run: sudo apt-get update -y && sudo apt-get install make -y && sudo apt-get install git -y && sudo apt-get install libcursesw5-dev -y && sudo apt-get install libcurl4-openssl-dev -y
