version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.04
      
    steps:
      - checkout
      
      - run: 
          command: |
            sudo apt-get update -y | sudo apt-get install make -y | sudo apt-get install git -y | sudo apt-get install gcc -y | sudo apt-get install libncursesw5-dev -y | sudo apt-get install libcurl4-openssl-dev -y
