version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.04
      
    steps:
      - checkout
      
      - run: sudo apt-get update -y
      - run: sudo apt-get install make -y
      - run: sudo apt-get install git -y
      - run: sudo apt-get install gcc -y
      - run: sudo apt-get install libncursesw5-dev -y
      - run: sudo apt-get install libcurl4-openssl-dev -y
